### ISSUE TITLE
raise ValueError('%s has host bits set' % self)

### ISSUE THREAD

**Issue by spirillen** [iv-org/smart-ipv6-rotator#27]
Following the guide at https://docs.invidious.io/ipv6-rotator/#if-you-are-running-invidious-in-docker will raise this issue

OS: Debian 12.6

```python
sudo python3.11 smart-ipv6-rotator.py run --ipv6range=IPv6/56
Deprecation warning https://docs.pyroute2.org/ipdb_toc.html
[INFO] You have IPv6 connectivity. Continuing.
[INFO] No cleanup of previous setup needed.
Traceback (most recent call last):
  File "/home/$user/Projects/github/smart-ipv6-rotator/smart-ipv6-rotator.py", line 4, in <module>
    main()
  File "/home/$user/Projects/github/smart-ipv6-rotator/smart_ipv6_rotator/__init__.py", line 280, in main
    args.func(args)
  File "/home/$user/Projects/github/smart-ipv6-rotator/smart_ipv6_rotator/__init__.py", line 70, in _parse_args
    return func(**params)
           ^^^^^^^^^^^^^^
  File "/home/$user/Projects/github/smart-ipv6-rotator/smart_ipv6_rotator/__init__.py", line 98, in run
    ipv6_network = IPv6Network(ipv6range)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ipaddress.py", line 2216, in __init__
    raise ValueError('%s has host bits set' % self)
ValueError: IPv6/56 has host bits set
```

**Comment by SamantazFox** [comment]
You need to replace `IPv6/56` with an IPv6 range that you own.

**Comment by spirillen** [comment]
> You need to replace `IPv6/56` with an IPv6 range that you own.

That is the range I own I add there ....

**Comment by spirillen** [comment]
```
ip -6 a | grep inet
    inet6 ::1/128 scope host 
    inet6 2001:41d0:700:133e::/56 scope global 
    inet6 fe80::a6bf:1ff:fe28:e742/64 scope link
```
```python
sudo python3.11 smart-ipv6-rotator.py run --ipv6range=2001: 41d0: 700:133e: :/56
Deprecation warning https: //docs.pyroute2.org/ipdb_toc.html
[INFO
] You have IPv6 connectivity. Continuing.
[INFO
] No cleanup of previous setup needed.
Traceback (most recent call last):
  File "/home/$USER/Projects/github/smart-ipv6-rotator/smart-ipv6-rotator.py", line 4, in <module>
    main()
  File "/home/$USER/Projects/github/smart-ipv6-rotator/smart_ipv6_rotator/__init__.py", line 280, in main
    args.func(args)
  File "/home/$USER/Projects/github/smart-ipv6-rotator/smart_ipv6_rotator/__init__.py", line 70, in _parse_args
    return func(**params)
           ^^^^^^^^^^^^^^
  File "/home/$USER/Projects/github/smart-ipv6-rotator/smart_ipv6_rotator/__init__.py", line 98, in run
    ipv6_network = IPv6Network(ipv6range)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ipaddress.py", line 2216, in __init__
    raise ValueError('%s has host bits set' % self)
ValueError: 2001: 41d0: 700:133e: :/56 has host bits set
```

**Comment by WardPearce** [comment]
no spaces

**Comment by spirillen** [comment]
> no spaces

well there isn't in the console, this is a paste in browser error 🤣

**Comment by unixfox** [comment]
Please have a look at the similar issues:
- https://github.com/iv-org/smart-ipv6-rotator/issues/20
- https://github.com/iv-org/smart-ipv6-rotator/issues/12

**Comment by spirillen** [comment]
Thanks @unixfox you spotted something I haven't, but the script still fails, just not the same error, this is a OVH if it makes any diff to the network setup

```python
sudo python3.11 smart-ipv6-rotator.py run --ipv6range=2001:41d0:700:1300::/56
Deprecation warning https://docs.pyroute2.org/ipdb_toc.html
[INFO] You have IPv6 connectivity. Continuing.
[INFO] No cleanup of previous setup needed.
[DEBUG] Debug info:
ranges --> ['2800:3f0:4000::/36', '2404:6800:4000::/36', '2c0f:fb50:4000::/36', '2607:f8b0:4000::/36', '2a00:1450:4000::/36', '2001:4860:4000::/36']
random_ipv6_address --> 2001:41d0:700:135e:184f:d1a0:c0bc:ee58
gateway --> 2001:41d0:700:13ff:ff:ff:ff:ff
interface_index --> 2
interface_name --> eno1
ipv6_subnet --> 2001:41d0:700:1300::/56
random_ipv6_address_mask --> 56
[Error]  Failed to remove the configured IPv6 subnets 2800:3f0:4000::/36,2404:6800:4000::/36,2c0f:fb50:4000::/36,2607:f8b0:4000::/36,2a00:1450:4000::/36,2001:4860:4000::/36
            May be expected if the route were not yet configured and that was a cleanup due to an error
            
[INFO] Finished cleaning up previous setup.
[INFO] Waiting for the propagation in the Linux kernel.
[ERROR] Failed to send the request for checking the new IPv6 address! The setup did not work!
        Your provider probably does not allow setting any arbitrary IPv6 address.
        Or did you correctly configure the IPv6 subnet to use?
       Exception:
HTTPConnectionPool(host='2606:4700::6812:7261', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7c96e7c2ebd0>, 'Connection to 2606:4700::6812:7261 timed out. (connect timeout=5)'))
```

## ipv6 ping test

```bash
ping -c 2 -6 leah.ns.cloudflare.com
PING leah.ns.cloudflare.com(leah.ns.cloudflare.com (2606:4700:50::adf5:3a81)) 56 data bytes
64 bytes from leah.ns.cloudflare.com (2606:4700:50::adf5:3a81): icmp_seq=1 ttl=53 time=1.34 ms
64 bytes from leah.ns.cloudflare.com (2606:4700:50::adf5:3a81): icmp_seq=2 ttl=53 time=1.35 ms

--- leah.ns.cloudflare.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 1.336/1.343/1.350/0.007 ms
```

## netplan

```yaml
    version: 2
    ethernets:
        eno1:
            accept-ra: false
            addresses:
            - 2001:41d0:700:133e::/56
```

**Comment by spirillen** [comment]
Maybe that you are testing against a endpoint that is blocking access :)

```bash
curl -g -6 -I http://[2606:4700::6812:7261]:80
HTTP/1.1 403 Forbidden
Date: Thu, 25 Jul 2024 00:03:10 GMT
Content-Type: text/plain; charset=UTF-8
Content-Length: 16
Connection: close
X-Frame-Options: SAMEORIGIN
Referrer-Policy: same-origin
Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Expires: Thu, 01 Jan 1970 00:00:01 GMT
Server: cloudflare
CF-RAY: 8a87e2a8b94cbbad-FRA
```

The same for lynx, it is also getting the 403, before redirecting to a crimeflare

```
   Please enable cookies.

Error 1003

   Ray ID: 8a87e58c0b5365a4 • 2024-07-25 00:05:09 UTC

Direct IP access not allowed

What happened?

   You've requested an IP address that is part of the Cloudflare network. A valid Host header must be supplied to reach the desired website.

What can I do?

   If you are interested in learning more about Cloudflare, please visit our website.
   Was this page helpful? (BUTTON) Yes (BUTTON) No
   Thank you for your feedback!

   Cloudflare Ray ID: 8a87e58c0b5365a4 • Your IP: (BUTTON) Click to reveal 2001:41d0:700:133e:: • Performance & insecurity by Cloudflare
```

**Comment by unixfox** [comment]
If you are using a virtual server (VPS) from OVH then the script won't work you can only have 1 IPV6 address in the range: https://help.ovhcloud.com/csm/en-gb-vps-configuring-ipv6?id=kb_article_view&sysparm_article=KB0047569

/128 and that's it.

**Comment by spirillen** [comment]
That isn't a bps, it is a full server with the /56 address range, but as mentioned. I suspect the file is failing cause of the test destication

**Comment by unixfox** [comment]
The script is working perfectly, it has been tested by more than hundred of users.

If it doesn't work for you, it means that your provider does not allow you to assign arbitrary IPv6 addresses. Maybe at OVH you need to assign them through the control panel for them to work? I don't know.

The point is that there is no bug in the script, it all depends on your IPv6 networking configuration.
